version: '2'
services:
    app:
      build: ./dckr/php

      links:
        - db

      volumes_from:
        - data
      environment:
        - XDEBUG_CONFI=remote_host="172.17.0.1"

    nginx:
      image: nginx:1.11

      ports:
        - 8000:8000
        - 9001:9000

      links:
        - app

      volumes:
        - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro

      volumes_from:
        - data

    db:
      image: mariadb

      volumes:
        - ./data/db:/var/lib/mysql

      volumes_from:
        - data

      environment:
        - MYSQL_ROOT_PASSWORD=root

    adminer:
      image: dockette/adminer:mysql-php7

      ports:
        - 10000:80

      links:
        - db

    data:
      image: busybox:latest

      volumes:
        - ./app:/srv
